wip: multi OS

diff --git a/bin/command-exists b/bin/command-exists
--- a/bin/command-exists
+++ b/bin/command-exists
@@ -1,6 +1,13 @@
 #!/usr/bin/env bash
 
+set -x
+echo "------------------------------"
+echo "command-exists: ${1}"
+echo "------------------------------"
+
 # Check if a program exists from a Bash script
 # SOURCE: https://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script
 
-command -v "$1" >/dev/null 2>&1 || { echo >&2 "I require ${1} but it's not installed.  Aborting."; exit 1; }
+command -v "${1}" >/dev/null 2>&1 || { echo >&2 "I require ${1} but it's not installed.  Aborting."; exit 1; }
+
+set +x
